2025-04-29 12:35:53 INFO: [RotationDatasetConfig] Init (log path: /home/labs/hornsteinlab/giliwo/NOVA_rotation/UMAP/UMAP_output/logs/290425_123553_578255_723548_giliwo_binbash.log; JOBID: 723548 Username: giliwo) JOBNAME: binbash
2025-04-29 12:35:53 INFO: [RotationDatasetConfig] NOVA_HOME=./NOVA_rotation/NOVA, NOVA_DATA_HOME=/home/labs/hornsteinlab/Collaboration/MOmaps/input
2025-04-29 12:35:53 ERROR: [Errno 2] No such file or directory: '/home/labs/hornsteinlab/giliwo/NOVA_rotation/attention_maps/test/embedding_output/pairs/testsets.npy'
Traceback (most recent call last):
  File "./NOVA_rotation/NOVA/runnables/generate_umaps_and_plot_test.py", line 75, in <module>
    generate_umaps(output_folder_path, config_path_data, config_path_plot)
  File "./NOVA_rotation/NOVA/runnables/generate_umaps_and_plot_test.py", line 34, in generate_umaps
    embeddings, labels = np.load(os.path.join(embeddings_folder, "testsets.npy"), allow_pickle=True), np.load(os.path.join(embeddings_folder, "testsets_labels.npy"), allow_pickle=True)
  File "/home/labs/hornsteinlab/giliwo/.conda/envs/nova/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/labs/hornsteinlab/giliwo/NOVA_rotation/attention_maps/test/embedding_output/pairs/testsets.npy'
